#' \code{wicedproj}: A package implementing the
#' Education Projection Model of the Wittgenstein Centre for Demography and Global Human Capital.
#'
#' @import dplyr
#' @import dtplyr
#' @docType package
#' @name wicedproj
NULL

#' Run the educational attainment projection
#'
#' Function \code{edproj} is the main front-end function
#' to run all steps involved in the projection. Currently
#' it is mandatory to include a target, as both trend and
#' target-attaining trajectories are estimated.
#'
#' @param x A dataframe in the correct input format (as generated by \code{wic_prepare}, for example)
#' @export
edproj <- function(x) {

  # list of countries that actually entered the estimation
  data_countries <- get_data_countries(x)

  x %>%
  estimate %>%
  process %>%
  ceiling(x) %>%
  export4popproj %>%
  identity
}

popN <- 1e4
